name: "run-aqa build with push to master"
on:
  push:
    branches:
      - master

jobs:
  openjdk: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'github-hosted'
        build_list: 'openjdk'
        target: '_jdk_custom'
  functional: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
        impl: 'openj9'
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'functional'
        target: '_floatSanityTests'
  system: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '11'
        targets: 'JDK_11'
        impl: 'openj9'
    - name: AQA
      uses: ./
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: 'system'
        target: '_DaaLoadTest_daa1'
